//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveDecisionSystemAPI.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    
    public partial class loan
    {
        [Key]
        public int LoanNum { get; set; }
        public int SupplierID { get; set; }
        public int BankNum { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public Nullable<int> initilAmount { get; set; }
        public Nullable<int> CurrentBalance { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
