//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CognitiveDecisionSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        [Key]
        public int SaleID { get; set; }
        public Nullable<System.DateTime> DATEOFSALE { get; set; }
        public int EmployeeId { get; set; }
        public int CustID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
    }
}
